[package]
name = "dd_dsp"
version = "0.1.0"
authors = ["Rob Saunders <rob@wearebrandnew.com>"]

[dependencies]
vst = { git = "https://github.com/rust-dsp/rust-vst" }
log = "0.3"
time = "0.1"
hound = "3.1.0"
basic_dsp="0.5"

[lib]
name = "dd_dsp"
